apiVersion: apps/v1
kind: Deployment
metadata:
  name:  person-api
spec:
  selector:
    matchLabels:
      app: person-api
  template:
    metadata:
      labels:
        app: person-api
    spec:
      containers:
        - name: person-api
          image: wirlleyd/jaeger-person-exemple:v8
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: person-env
          ports:
            - containerPort: 80