apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wallet-api
spec:
  selector:
    matchLabels:
      app: wallet-api
  template:
    metadata:
      labels:
        app: wallet-api
    spec:
      containers:
        - name: wallet-api
          image: wirlleyd/jaeger-client-wallet:v3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80